### PR TITLE
https now works

### PR DESCRIPTION
**Pull request by asl97**

### CODE REVIEW

**Comment by jperkin** [comment]
Sorry, I missed this! Have merged it now and published version 1.6 with the changes. Thanks!

**Comment by iptvcrugalde** [comment]
www.iptvlatina.cr_liverawcine.m3u

- IMG-20201228-WA0014

1. 

- [](url)

**Comment by iptvcrugalde** [comment]
www.iptvlatina.cr_liverawcine.m3u

**Comment by iptvcrugalde** [comment]
#EXTM3U 
www.iptvlatina.cr_liverawcine.m3u

**Pull request merged**
